import type { Metadata } from 'next';
import { Gantari } from 'next/font/google';
import '../styles/globals.css';
import LayoutContainer from "../processes/layoutContainer/LayoutContainer";
import WithStoreProvider from "../processes/store-provider/WithStoreProvider";

const gantari = Gantari({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={gantari.className} style={{marginRight: '0px !important'}}>
      <WithStoreProvider>
        <LayoutContainer>
            {children}
        </LayoutContainer>
      </WithStoreProvider>
      </body>
    </html>
  )
}
